version: '3'
# - docker-compose 파일의 버전을 정의함.
# - 여기서 '버전 3'은 Docker Compose 의 포맷을 나타냄.
#   버전에 따라 사용할 수 있는 기능이 다르며, '버전 3'은 여러 최신 기능들을 지원함.




# < docker compose 파일의 핵심 구성 요소 service >

# - 이 services 섹션은 이 아래에 컨테이너로 실행될 여러 각 service 들을 정의하는 루트 영역임.
#   '하나의 service'는 '하나의 컨테이너'를 의미하며,
#   이 아래에서 우리는 'app 서비스' 와 'db 서비스' 이렇게 2개의 서비스를 정의할 것임.
#   각각의 service 는 애플리케이션 또는 DB 와 같은 역할을 담당함.
# - 비유하자면, 마치 여러 개의 방을 가진 집을 상상하는 것과 같음.
#   'app'은 거실이고, 'db'는 부엌임.
#   각각의 방은 다른 목적을 가지고 있지만, 결국 하나의 집 안(Docker Compose 안)에 함께 있음.
services:




  # < Node.js 애플리케이션을 실행하는 service 를 정의하는 app >
  
  # - 이 서비스 app 은 컨테이너로 실행되며,
  #   이 컨테이너 안에서 Node.js 애플리케이션이 실행됨.
  # - 이 섹션은 애플리케이션의 빌드 방법, 포트 설정, 환경 변수 등을 정의함.
  app:




    # < Docker 에게 현재 디렉토리 안에 있는 Dockerfile 을 사용하여 애플릴케이션의 이미지를 빌드하라고 명령하는 명령어 >

    # - '.'
    #   : '현재 디렉토리'를 의미함. 즉, 'docker-compose.yml 파일'이 위치한 디렉토리에서 Dockerfile 을 찾아서
    #     이미지를 빌드하라고 Docker 에게 명령하는 것임.
    build: .




    # < '내 로컬 호스트 시스템' <--> 'app 애플리케이션'  간의 포트 매핑 설정 >

    # - 'ports'
    #   : - Docker Compose 에서 사용하는 명령어로, 포트 매핑을 설정할 때 사용됨.
    #     - 이 명령은 'Docker 컨테이너 내부에서 사용하는 포트('두 번째 3000')'를 외부에 공개하여,
    #       '내 컴퓨터 로컬 호스트, 즉 Docker 가 실행중인 컴퓨터의 포트('첫 번째 3000')' 에서
    #       해당 Docker 컨테이너에 접근할 수 있게 해줌.
    #     - 사용하는 목적
    #       : 외부 네트워크 또는 로컬 호스트 시스템에서 '이 NestJS 애플리케이션 app' 에 접근하기 위해서는,
    #         이 Docker 컨테이너 내부에서 실행되는 애플리케이션이 사용하는 포트가 외부로 열려 있어야 함.
    #         이때 'ports' 설정을 통해 '로컬 호스트(내 컴퓨터)'와 'Docker 컨테이너' 간의 '포트 연결을 설정하는 것임'!!!
    ports:

      # ******중요*******
      # - '첫 번째 포트 3000' --> 로컬 호스트(= 서버 = 내 컴퓨터)의 포트
      #   : - 첫 번째 포트 3000 은 '로컬 호스트 컴퓨터(= 서버)에서 사용할 포트 번호'임.
      #       즉, 외부에서 오는 요청(HTTP 요청)은 로컬 호스트 시스템의 3000번 포트로 들어오게 됨.
      #     ***중요***
      #     - 비유하자면, '호스트 포트(= 서버)'는 '아파트 현관문의 현관 비밀번호'와 같음.
      #       외부 사람들이 우리 집을 방문할 때, 이 현관문을 통해서만 우리 집으로 들어올 수 있음.
      #     ***중요***
      #     - 이 호스트 포트(= 서버)가 열려 있지 않으면, 외부에서 들어오는 네트워크 요청을 받을 수 없다!
      #       예를 들어, 실제 웹서비스 사용자가 웹 브라우저에서 'http://localhost:3000'을 통해 접속할 때,
      #       로컬 호스트(= 내 컴퓨터 = 서버)의 3000번 포트로 요청이 들어오게 된다!!



      # - '두 번째 포트 3000' --> Docker 컨테이너의 내부에서 사용되는 포트
      #   : - 현재 이 app 서비스(= app Docker 컨테이너) 에서 실행중인 애플리케이션(NestJS)이 사용하는 포트임.
      #       여기서 NestJS 는 기본적으로 포트 3000에서 실행되며, 
      #       외부에서 들어온 요청은 이 포트 3000 을 통해 app 애플리케이션으로 들어와 처리되는 것임.
      #    ***중요***
      #    - 비유하자면, '컨테이너 포트'는 '우리 집 내부에 있는 방의 번호'와 같음.
      #      '우리 집 현관문(= 호스트 포트)'을 통해 손님이 들어오면,
      #      그 손님을 '3000번 방(= Docker 컨테이너의 내부 포트)'에서 실제로 맞아들이는 것임.
      #    - 외부에서 들어온 요청이 Docker 컨테이너의 포트로 전달되어야만,
      #      그 Docker 컨테이너의 애플리케이션이 정상적응로 동작할 수 있는 것임!!
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db             # MySQL 컨테이너의 서비스 이름을 DB_HOST로 설정
      - DB_PORT=3306           # MySQL의 기본 포트
      - DB_USERNAME=root       # MySQL 기본 사용자명
      - DB_PASSWORD=1234    # MySQL 비밀번호
      - DB_NAME=healthcraft    # ***MySQL 워크벤치에 설정된 이 프로젝트와 연동되어 있는 DB 스키마 이름과 일치해야 한다!!*** 




    # ***중요***
    # < 서비스 간의 종속성 정의 >

    # - 여기서는 app 서비스가 실행되기 전에 '아래에서 정의된 이름이 'db'인 서비스(= 컨테이너)가 먼저 실행되어야 한다는 것으 의미함.       
    depends_on:
      - db                    # db 컨테이너가 먼저 시작되어야 함



  # < Docker Compose 파일에서 MySQL DB를 담당 실행할 Docker 컨테이너의 '이름'을 'db'로 지정하는 것임 >

  # - 다른 컨테이너(e.g: 여기서는 위의 app 컨테이너(= NestJS 애플리케이션))가 이 'db'라는 이름을 사용하여
  #   네트워크 상에서 MySQL DB 에 접근하게 되는 것임.
  # - Docker Compose 는 서비스들(= Docker 컨테이너들) 간의 네트워크를 자동으로 설정해주기 떄문에,
  #   위 app 애플리케이션은 'db'라는 이름만으로 이 MySQL 컨테이너와 통신할 수 있게 되는 것임.
  db:
    


    # - Docker Hub 에서 'MySQL 5.7 버전의 공식 이미지'를 다운로드하여 사용하라는 의미임.
    #   이 이미지를 사용하여 MySQL 서버가 이 'db 컨테이너' 안에서 실행됨.
    # - Docker 는 '이미지'라는 개념을 사용하여, 특정 소프트웨어(이 경우 MySQL)를 실행하는 데 필요한 모든 파일과 설정을 포함한
    #   패키지를 만들어줌.
    #   따라서, 이 코드는 MySQL DB 서버를 '이 Docker 컨테이너 안에서 자동으로 실행할 수 있게 해줌!!'
    # - 비유하자면, 이 '공식 이미지'를 사용하는 것은, 마치 설치된 소프트웨어 패키지를 다운로드해 즉시 실행하는 것과 같음.
    #   예를 들어, 인터넷에서 미리 설정된 MySQL 서버 설치 파일을 다운로드해서 바로 사용할 수 있게 하는 것과 유사함.
    # ***중요***
    # - 이 설정은 MySQL 데이터베이스가 'db 컨테이너' 안에서 자동으로 실행되도록 하며,
    #   개발자가 별도로 MySQL 을 설치하거나 설정할 필요 없이 데이터를 관리할 수 있도록 해줌.
    #   즉, MySQL 서버를 실행하는 복잡한 과정을 자동화하고, 
    #   즉시 사용할 수 있는 DB 서버를 제공함.
    image: mysql:5.7           # MySQL 5.7 이미지 사용
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: healthcraft   # ***MySQL 워크벤치에 설정된 이 프로젝트와 연동되어 있는 DB 스키마 이름과 일치해야 한다!!***


    # < '내 로컬 호스트 시스템' <--> 'db 애플리케이션'  간의 포트 매핑 설정 >

    # - 비유하자면, 외부 손님이 집에 들어오려면 '내 집 현관문(= 첫 번째 3306 = 내 로컬 호스트의 포트 번호)'을 통해 우선 들어와야 하고,
    #   그 다음 '내 집 안의 방(= 두 번째 3306 = db 애플리케이션의 포트 번호)'으로 들어올 수 있게 되는 것임.
    # - 즉, '내 집 안의 방(= 두 번째 3306 = db 애플리케이션의 포트 번호)'에서 '실제로 MySQL 서버가 작동하는 것임!!''
    ports:
      - "3306:3306"
